from selenium import webdriver
import time
driver = webdriver.Chrome("./chromedriver.exe")
try:
    driver.implicitly_wait(5)
    driver.maximize_window()
    driver.get("http://127.0.0.1/forum.php")
    name=driver.find_element_by_name("username")
    name.send_keys("admin")
    password=driver.find_element_by_name("password")
    password.send_keys("shj1996")
    denglu=driver.find_element_by_css_selector(".fastlg_l button")
    denglu.click()
    time.sleep(2)
    driver.switch_to.window(driver.current_window_handle)
    moren=driver.find_element_by_css_selector(".fl_tb a")
    moren.click()
    driver.switch_to.window(driver.current_window_handle)
    biaoti=driver.find_element_by_css_selector(".pbt input")
    biaoti.send_keys("我的第一个帖子")
    time.sleep(2)
    content=driver.find_element_by_xpath("//textarea")
    content.send_keys("毒奶粉真好玩！！！！")
    fabiao = driver.find_element_by_css_selector(".ptm button")
    fabiao.click()
    time.sleep(2)
    replaycontent=driver.find_element_by_xpath("//textarea")
    replaycontent.send_keys("稳啊，老哥!")
    fabiao = driver.find_element_by_css_selector(".ptm button")
    fabiao.click()
    tuichu=driver.find_element_by_partial_link_text("退出")
    tuichu.click()

finally:
    quit()